Back-end/database/1006/02_db_workshop_skeleton/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

Back-end/database/1006/02_db_workshop_skeleton/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comment/create/', views.comment_create, name='comment_create'),
    path('<int:comment_pk>/comment/delete/', views.comment_delete, name='comment_delete'),
]

Back-end/database/1006/02_db_workshop_skeleton/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

Back-end/database/1006/02_db_workshop_skeleton/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    

    # 댓글 정보를 저장하기 위한 모델 클래스 작성.
class Comment(models.Model): # 모델스에서 모델을 상속
    content = models.CharField(max_length=200)
    # 어떤 게시글에 댓글이 달렸는지 게시글 정보를 저장하기 위한 F.K
    # F.K는 1:N 관계에서 N에 위치하면 된다.
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

Back-end/database/1006/02_db_workshop_skeleton/articles/forms.py
from django import forms
from .models import Article, Comment

# class ArticleForm(forms.Form):
#     REGION_A = 'sl'
#     REGION_B = 'dj'
#     REGION_C = 'gj'
#     REGION_D = 'gm'
#     REGION_E = 'bs'
#     REGIONS_CHOICES = [
#         (REGION_A, '서울'),
#         (REGION_B, '대전'),
#         (REGION_C, '광주'),
#         (REGION_D, '구미'),
#         (REGION_E, '부산'),
#     ]
#     title = forms.CharField(max_length=10)
#     content = forms.CharField(widget=forms.Textarea())
#     region = forms.ChoiceField(choices=REGIONS_CHOICES, widget=forms.Select())

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs={
                'class': 'my-title', 
                'placeholder': 'Enter the title',
                'maxlength': 10,
            }
        ),
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'my-content',
                'placeholder': 'Enter the content',
                'rows': 5,
                'cols': 50,
            }
        ),
        error_messages={
            'required': 'Please enter your content'
        }
    )
    
    class Meta:
        model = Article
        fields = ('title','content',)
        # exclude = ('author',)

class CommentForm(forms.ModelForm):
    '''
    게시글을 조회했을 때 (detail) 댓글을 다는 것이 일반적임.
    게시글의 detail 에서 CommentForm을 사용해서 
    유저들이 작성할 수 있도록 하여야함. 
    '''
    class Meta:
        model = Comment
        fields = ('content',)

Back-end/database/1006/02_db_workshop_skeleton/articles/views.py
from django.urls import is_valid_path
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST, require_safe

# Create your views here.
@require_safe
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST) 
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    # print(form.errors)
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)


@require_safe
def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    # 댓글 작성을 위한 입력 폼
    comment_form = CommentForm()
    # 댓글 정보를 가져오자.
    # Comment.objects.all() 이렇게 가지고 오면 1번 글에서 2번글의 댓글도 보인다.
    # Comment.objects.get() 이렇게 가지고 오면 하나만 작성된다.
    comments = Comment.objects.filter(article=article)  # 앞은 필드명 뒤는 위의 article
    context = {
        'article': article,
        # 반드시 html에서 사용할 수 있도록 comment form을 전달해야함.
        'comment_form': comment_form,   
        'comments':comments,
    }
    return render(request, 'articles/detail.html', context)


@require_POST
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    # 글쓴이가 아닌 사람이 삭제하려고 하는 것을 방지.
    if request.user != article.author:
        return redirect('articles:detail', article.pk)

    if request.user.is_authenticated:
        article.delete()
        return redirect('articles:index')
    return redirect('articles:detail', article.pk)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)

    # 글쓴이가 아닌 사람이 수정하려고 하는 것을 방지.
    if request.user != article.author:
        return redirect('articles:detail', article.pk)

    if request.method == 'POST':
        # Create a form to edit an existing Article,
        # but use POST data to populate the form.
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article.pk)
    else:
        # Creating a form to change an existing article.
        form = ArticleForm(instance=article)
    context = {
        'article': article,
        'form': form,
    }
    return render(request, 'articles/update.html', context)

@require_POST
def comment_create(request, article_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    comment_form = CommentForm(request.POST)
    article = Article.objects.get(pk=article_pk)  # 댓글의 글 데이터를 넣기 위해 글 정보를 불러와야함.
    if comment_form.is_valid():
        # 그냥 save를 하면 not null constraint failed
        comment = comment_form.save(commit=False) # comment : DB에 저장되기 전 사용자가 입력한 comment
        comment.article = article                 # 글 정보를 직접 입력
        comment.save()                            # 최종 저장.
        return redirect('articles:detail', article_pk)
    # 유효성 검사를 통과하지 못하는 경우는
    # 리다이렉트를 하게 되면 에러정보가 전달되지 못함.
    # 그래서 직접 렌더를 해야한다.
    comments = Comment.objects.filter(article=article)
    context = {
        'comment_form':comment_form,
        'article':article,
        'comments':comments,
    }
    return render(request, 'articles/detail.html', context)

@require_POST
def comment_delete(request, comment_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    # 어떤 댓글을 가지고 올까?
    comment = Comment.objects.get(pk=comment_pk)
    # 삭제하기 전에 게시글 정보를 가지고 온다 redirect할 때 필요하기 때문에!
    article = comment.article
    comment.delete()

    return redirect('articles:detail', article.pk)

Back-end/database/1006/02_db_workshop_skeleton/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock %}

Back-end/database/1006/02_db_workshop_skeleton/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>DETAIL</h2>
  <h3>{{ article.pk }} 번째 글</h3>
  <hr>
  <p>제목: {{ article.title }}</p>
  <p><b>작성자: {{article.author}}</b></p>
  <p>내용: {{ article.content }}</p>
  <p>작성 시각: {{ article.created_at }}</p>
  <p>수정 시각: {{ article.updated_at }}</p>
  <hr>
  {% comment %} 작성자만 글을 수정하고 삭제할 수 있도록 안내 {% endcomment %}
  {% if request.user == article.author %}
  <a href="{% url 'articles:update' article.pk %}">UPDATE</a><br>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  {% endif %}
  <a href="{% url 'articles:index' %}">[back]</a>
  {% comment %} 댓글 입력 창 추가 {% endcomment %}
  <hr>
  {% comment %} 
    action을 비워두면 detail로 댓글 생성 요청이 가기 때문에
    action을 다른 주소로 요청할 수 있게 작성해야함.
    이 때 게시글 정보도 같이 전달해줘야함!

    로그인한 사람만 댓글 작성을 할 수 있도록!!
  {% endcomment %}
  {% if user.is_authenticated %}
  <form action="{% url 'articles:comment_create' article.pk %}" method="POST">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button>댓글달기</button>
  </form>
  {% else%}
    <a href="{% url 'accounts:login'%}">댓글은 로그인한 작성자만 쓸 수 있습니다.</a>
  {% endif %}
  {% comment %} 
    여기에 작성한 댓글들이 보여지게 처리!!
  {% endcomment %}
  <ul>
    {% for comment in comments %}
      <li class="d-flex">
        <div>{{ comment.content }}</div>
        {% comment %} 댓글 삭제를 위한 버튼 {% endcomment %}
        {% if user.is_authenticated %}
        <form action="{% url 'articles:comment_delete' comment.pk %}" method="POST">
          {% csrf_token %}
          <button>X</button>
        </form>
        {% endif %}
      </li>
    {% empty %}
      <p>댓글이 없어요..</p>
    {% endfor %}
  </ul>
  {% comment %} 
  {% for comment in article.comment_set.all %}
  <p>{{comment}}</p>
  {% endfor %} 
  {% endcomment %}
{% endblock  %}

Back-end/database/1006/02_db_workshop_skeleton/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Articles</h1>
  {% if user.is_authenticated %}
    <a href="{% url 'articles:create' %}">[CREATE]</a>
  {% else %}
    <a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인하세요]</a>
  {% endif %}
  <hr>
  {% for article in articles %}
  <p><b>작성자: {{ article.author }}</b></p>
    <p>글 번호: {{ article.pk }}</p>
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <a href="{% url 'articles:detail' article.pk %}">[detail]</a>
    <hr>
  {% endfor %}
{% endblock %}

Back-end/database/1006/02_db_workshop_skeleton/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">[back]</a>
{% endblock %}